/**
 * Apply Logbook's App Store configuration to the iOS project (#1420, #531, #538).
 *
 * `ios/` is generated by `npx cap add ios --packagemanager SPM` and IS committed
 * (README → Native iOS build): it is the App Store build, so the icon, launch
 * screen, privacy manifest and build settings live in git like any other
 * shipping artifact. This script is what makes the project reproducible when
 * someone regenerates it anyway — it re-applies everything the stock Capacitor
 * template lacks, and it runs from the `capacitor:sync:after` hook in
 * package.json, i.e. on every `npx cap sync` / `npm run cap:build`. Every
 * transform is idempotent, so on a project that already carries the config the
 * only thing that changes is the version stamp (5).
 *
 *   1. Info.plist gains the two HealthKit usage strings. Without them iOS kills
 *      the app the moment it asks for Health access, and App Review rejects the
 *      build. They are user-facing copy, which is why they are versioned here
 *      rather than typed into Xcode.
 *   2. App/App.entitlements declares `com.apple.developer.healthkit`, and the App
 *      target's Debug/Release configurations point CODE_SIGN_ENTITLEMENTS at it —
 *      the file-level equivalent of ticking "HealthKit" under Signing &
 *      Capabilities. Xcode reads the capability back from the entitlements file.
 *   3. IPHONEOS_DEPLOYMENT_TARGET is raised to 16.0 (#531).
 *   4. Info.plist declares ITSAppUsesNonExemptEncryption = false — Logbook uses
 *      only HTTPS/system TLS, which is exempt, and without the key every
 *      TestFlight upload stops on the export-compliance questionnaire.
 *   5. TARGETED_DEVICE_FAMILY is iPhone-only (#539): iPad would add screenshot
 *      sizes, a review surface and layouts nobody has run.
 *   6. App/App/PrivacyInfo.xcprivacy (#538) — Apple's privacy manifest — is
 *      written and wired into the App target (file reference, group child and
 *      Copy Bundle Resources), the four pbxproj edits Xcode makes when a file is
 *      dragged in. Capacitor's own frameworks ship their manifests inside their
 *      xcframeworks; this one covers the APP: what Logbook collects (email, user id,
 *      workouts, bodyweight, scrubbed crash reports) and the required-reason API
 *      the bridge and @capacitor/preferences use (UserDefaults, CA92.1).
 *   7. MARKETING_VERSION is stamped from package.json's version and
 *      CURRENT_PROJECT_VERSION from the commit count on the current branch, so
 *      every archive cut from master carries a build number App Store Connect
 *      accepts as newer than the last one, with nothing to bump by hand (#540).
 *      Skipped when git is unavailable.
 *
 * A no-op (exit 0, one line of output) when `ios/` is absent, so `cap sync` for
 * another platform is unaffected.
 *
 * The transforms are exported so scripts/__tests__/configure-ios.test.mjs can run
 * them against the real Capacitor template AND against the committed project.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { execFileSync } from 'node:child_process'

const __dirname = dirname(fileURLToPath(import.meta.url))

/** Copy Apple shows in the HealthKit permission sheet. Keep honest and specific. */
export const HEALTH_USAGE_STRINGS = Object.freeze({
  NSHealthUpdateUsageDescription: 'Logbook adds the bodyweight you log to Apple Health.',
  // The sync never asks for read access; this string is required anyway because
  // Logbook queries the samples it wrote itself (to avoid writing one twice), and
  // iOS treats any HealthKit query as a read.
  NSHealthShareUsageDescription:
    'Logbook checks Health for weigh-ins it already added, so it never adds one twice.',
})

export const ENTITLEMENTS_RELATIVE_PATH = 'App/App.entitlements'

export const ENTITLEMENTS_XML = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.healthkit</key>
	<true/>
	<key>com.apple.developer.healthkit.access</key>
	<array/>
</dict>
</plist>
`

export const MIN_DEPLOYMENT_TARGET = '16.0'

/** iPhone only for v1 (#539). `"1,2"` is the template's iPhone + iPad. */
export const DEVICE_FAMILY = '1'

/**
 * Export compliance (#540): Logbook's only cryptography is HTTPS / system TLS, which
 * is exempt, so the answer is `false` — and declaring it in the plist is what
 * skips the questionnaire that otherwise stops every TestFlight upload.
 */
export const EXPORT_COMPLIANCE_KEY = 'ITSAppUsesNonExemptEncryption'

/** Relative to ios/App, like ENTITLEMENTS_RELATIVE_PATH: the file sits beside Info.plist. */
export const PRIVACY_MANIFEST_RELATIVE_PATH = 'App/PrivacyInfo.xcprivacy'

/**
 * Apple privacy manifest (#538). Data types mirror what the App Privacy
 * questionnaire in App Store Connect must say (docs/app-store/); keep the two
 * in step. Everything is collected for app functionality only, nothing is used
 * for tracking, and crash/performance data (Sentry, `sendDefaultPii: false`,
 * IP scrubbed — LIFT-533) is not linked to the user.
 */
export const PRIVACY_MANIFEST_XML = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTracking</key>
	<false/>
	<key>NSPrivacyTrackingDomains</key>
	<array/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array>
		<dict>
			<key>NSPrivacyCollectedDataType</key>
			<string>NSPrivacyCollectedDataTypeEmailAddress</string>
			<key>NSPrivacyCollectedDataTypeLinked</key>
			<true/>
			<key>NSPrivacyCollectedDataTypeTracking</key>
			<false/>
			<key>NSPrivacyCollectedDataTypePurposes</key>
			<array>
				<string>NSPrivacyCollectedDataTypePurposeAppFunctionality</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyCollectedDataType</key>
			<string>NSPrivacyCollectedDataTypeUserID</string>
			<key>NSPrivacyCollectedDataTypeLinked</key>
			<true/>
			<key>NSPrivacyCollectedDataTypeTracking</key>
			<false/>
			<key>NSPrivacyCollectedDataTypePurposes</key>
			<array>
				<string>NSPrivacyCollectedDataTypePurposeAppFunctionality</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyCollectedDataType</key>
			<string>NSPrivacyCollectedDataTypeFitness</string>
			<key>NSPrivacyCollectedDataTypeLinked</key>
			<true/>
			<key>NSPrivacyCollectedDataTypeTracking</key>
			<false/>
			<key>NSPrivacyCollectedDataTypePurposes</key>
			<array>
				<string>NSPrivacyCollectedDataTypePurposeAppFunctionality</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyCollectedDataType</key>
			<string>NSPrivacyCollectedDataTypeHealth</string>
			<key>NSPrivacyCollectedDataTypeLinked</key>
			<true/>
			<key>NSPrivacyCollectedDataTypeTracking</key>
			<false/>
			<key>NSPrivacyCollectedDataTypePurposes</key>
			<array>
				<string>NSPrivacyCollectedDataTypePurposeAppFunctionality</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyCollectedDataType</key>
			<string>NSPrivacyCollectedDataTypeCrashData</string>
			<key>NSPrivacyCollectedDataTypeLinked</key>
			<false/>
			<key>NSPrivacyCollectedDataTypeTracking</key>
			<false/>
			<key>NSPrivacyCollectedDataTypePurposes</key>
			<array>
				<string>NSPrivacyCollectedDataTypePurposeAppFunctionality</string>
			</array>
		</dict>
		<dict>
			<key>NSPrivacyCollectedDataType</key>
			<string>NSPrivacyCollectedDataTypePerformanceData</string>
			<key>NSPrivacyCollectedDataTypeLinked</key>
			<false/>
			<key>NSPrivacyCollectedDataTypeTracking</key>
			<false/>
			<key>NSPrivacyCollectedDataTypePurposes</key>
			<array>
				<string>NSPrivacyCollectedDataTypePurposeAppFunctionality</string>
			</array>
		</dict>
	</array>
	<key>NSPrivacyAccessedAPITypes</key>
	<array>
		<dict>
			<key>NSPrivacyAccessedAPIType</key>
			<string>NSPrivacyAccessedAPICategoryUserDefaults</string>
			<key>NSPrivacyAccessedAPITypeReasons</key>
			<array>
				<string>CA92.1</string>
			</array>
		</dict>
	</array>
</dict>
</plist>
`

// Fixed pbxproj object ids for the manifest wiring: Xcode wants 24 hex chars,
// and fixed ids keep a regenerated project byte-identical to the committed one.
export const PRIVACY_MANIFEST_FILE_REF_ID = '1425A0000000000000000001'
export const PRIVACY_MANIFEST_BUILD_FILE_ID = '1425A0000000000000000002'

function escapeXml(text) {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

/** Insert one entry before the closing `</dict>` of the TOP-LEVEL plist dict. */
function insertTopLevelPlistEntry(plistXml, entry) {
  const closing = plistXml.lastIndexOf('</dict>')
  if (closing === -1) throw new Error('Info.plist: no closing </dict> found')
  return plistXml.slice(0, closing) + entry + plistXml.slice(closing)
}

/**
 * Insert any missing usage string into the top-level Info.plist dictionary.
 * Keys already present (from an earlier run, or hand-set in Xcode) are left
 * exactly as they are.
 */
export function applyHealthUsagePlist(plistXml) {
  let out = plistXml
  for (const [key, value] of Object.entries(HEALTH_USAGE_STRINGS)) {
    if (out.includes(`<key>${key}</key>`)) continue
    out = insertTopLevelPlistEntry(out, `\t<key>${key}</key>\n\t<string>${escapeXml(value)}</string>\n`)
  }
  return out
}

/** Declare the app exempt from export compliance (see EXPORT_COMPLIANCE_KEY). */
export function applyExportCompliancePlist(plistXml) {
  if (plistXml.includes(`<key>${EXPORT_COMPLIANCE_KEY}</key>`)) return plistXml
  return insertTopLevelPlistEntry(plistXml, `\t<key>${EXPORT_COMPLIANCE_KEY}</key>\n\t<false/>\n`)
}

/**
 * Point every build configuration that owns the app's Info.plist at the
 * entitlements file. Only the App target's configurations carry
 * `INFOPLIST_FILE = App/Info.plist;`, so the project-level ones are untouched.
 */
export function applyEntitlementsSetting(pbxproj) {
  if (pbxproj.includes('CODE_SIGN_ENTITLEMENTS')) return pbxproj
  return pbxproj.replace(
    /^(\s*)INFOPLIST_FILE = App\/Info\.plist;$/gm,
    (_, indent) => `${indent}CODE_SIGN_ENTITLEMENTS = ${ENTITLEMENTS_RELATIVE_PATH};\n${indent}INFOPLIST_FILE = App/Info.plist;`,
  )
}

/** Raise (never lower) every IPHONEOS_DEPLOYMENT_TARGET below `minimum`. */
export function applyDeploymentTarget(pbxproj, minimum = MIN_DEPLOYMENT_TARGET) {
  const [minMajor, minMinor = 0] = minimum.split('.').map(Number)
  return pbxproj.replace(/IPHONEOS_DEPLOYMENT_TARGET = (\d+)(?:\.(\d+))?;/g, (match, major, minor = '0') => {
    const below = Number(major) < minMajor || (Number(major) === minMajor && Number(minor) < minMinor)
    return below ? `IPHONEOS_DEPLOYMENT_TARGET = ${minimum};` : match
  })
}

/** iPhone only (#539). */
export function applyDeviceFamily(pbxproj, family = DEVICE_FAMILY) {
  return pbxproj.replace(/TARGETED_DEVICE_FAMILY = (?:"[^"]*"|[^;]+);/g, `TARGETED_DEVICE_FAMILY = ${family};`)
}

/**
 * Stamp the App target's version pair. Either half may be omitted (left as is).
 * MARKETING_VERSION / CURRENT_PROJECT_VERSION only occur in the App target's
 * configurations in the template, so this cannot reach the project level.
 */
export function applyVersion(pbxproj, { marketingVersion, buildNumber } = {}) {
  let out = pbxproj
  if (marketingVersion) out = out.replace(/MARKETING_VERSION = [^;]+;/g, `MARKETING_VERSION = ${marketingVersion};`)
  if (buildNumber) out = out.replace(/CURRENT_PROJECT_VERSION = [^;]+;/g, `CURRENT_PROJECT_VERSION = ${buildNumber};`)
  return out
}

function insertAfter(text, anchor, insertion, what) {
  const idx = text.indexOf(anchor)
  if (idx === -1) throw new Error(`project.pbxproj: cannot find ${what} — has the Capacitor template changed shape?`)
  const at = idx + anchor.length
  return text.slice(0, at) + insertion + text.slice(at)
}

/**
 * Wire App/App/PrivacyInfo.xcprivacy into the App target: the PBXBuildFile and
 * PBXFileReference objects, a child of the `App` group (beside Info.plist) and
 * an entry in the Copy Bundle Resources phase. Idempotent on the file name.
 */
export function applyPrivacyManifestProject(pbxproj) {
  if (pbxproj.includes('PrivacyInfo.xcprivacy')) return pbxproj
  const ref = PRIVACY_MANIFEST_FILE_REF_ID
  const build = PRIVACY_MANIFEST_BUILD_FILE_ID
  let out = pbxproj
  out = insertAfter(
    out,
    '/* Begin PBXBuildFile section */\n',
    `\t\t${build} /* PrivacyInfo.xcprivacy in Resources */ = {isa = PBXBuildFile; fileRef = ${ref} /* PrivacyInfo.xcprivacy */; };\n`,
    'the PBXBuildFile section',
  )
  out = insertAfter(
    out,
    '/* Begin PBXFileReference section */\n',
    `\t\t${ref} /* PrivacyInfo.xcprivacy */ = {isa = PBXFileReference; lastKnownFileType = text.xml; path = PrivacyInfo.xcprivacy; sourceTree = "<group>"; };\n`,
    'the PBXFileReference section',
  )
  const groupAnchor = /( \/\* App \*\/ = \{\n\t\t\tisa = PBXGroup;\n\t\t\tchildren = \(\n)/
  if (!groupAnchor.test(out)) throw new Error('project.pbxproj: cannot find the App group')
  out = out.replace(groupAnchor, `$1\t\t\t\t${ref} /* PrivacyInfo.xcprivacy */,\n`)
  const resourcesAnchor = /(isa = PBXResourcesBuildPhase;\n\t\t\tbuildActionMask = \d+;\n\t\t\tfiles = \(\n)/
  if (!resourcesAnchor.test(out)) throw new Error('project.pbxproj: cannot find the Resources build phase')
  out = out.replace(resourcesAnchor, `$1\t\t\t\t${build} /* PrivacyInfo.xcprivacy in Resources */,\n`)
  return out
}

/** Every pbxproj transform except the version stamp (which needs inputs). */
export function applyProjectSettings(pbxproj) {
  return applyPrivacyManifestProject(applyDeviceFamily(applyDeploymentTarget(applyEntitlementsSetting(pbxproj))))
}

/** Every Info.plist transform. */
export function applyPlistSettings(plistXml) {
  return applyExportCompliancePlist(applyHealthUsagePlist(plistXml))
}

/**
 * Apply every transform to the project under `iosDir` (the `ios/` directory).
 * Returns what changed so a caller (or the test) can assert idempotency.
 * `version` is optional: `{ marketingVersion, buildNumber }`.
 */
export function configureIosProject(iosDir, { version } = {}) {
  const plistPath = join(iosDir, 'App', 'App', 'Info.plist')
  const pbxprojPath = join(iosDir, 'App', 'App.xcodeproj', 'project.pbxproj')
  const entitlementsPath = join(iosDir, 'App', ENTITLEMENTS_RELATIVE_PATH)
  const manifestPath = join(iosDir, 'App', PRIVACY_MANIFEST_RELATIVE_PATH)
  if (!existsSync(plistPath) || !existsSync(pbxprojPath)) return { skipped: true, changed: [] }

  const changed = []
  const plist = readFileSync(plistPath, 'utf8')
  const nextPlist = applyPlistSettings(plist)
  if (nextPlist !== plist) {
    writeFileSync(plistPath, nextPlist)
    changed.push('Info.plist')
  }

  if (!existsSync(entitlementsPath) || readFileSync(entitlementsPath, 'utf8') !== ENTITLEMENTS_XML) {
    writeFileSync(entitlementsPath, ENTITLEMENTS_XML)
    changed.push(ENTITLEMENTS_RELATIVE_PATH)
  }

  if (!existsSync(manifestPath) || readFileSync(manifestPath, 'utf8') !== PRIVACY_MANIFEST_XML) {
    writeFileSync(manifestPath, PRIVACY_MANIFEST_XML)
    changed.push(PRIVACY_MANIFEST_RELATIVE_PATH)
  }

  const pbxproj = readFileSync(pbxprojPath, 'utf8')
  const nextPbxproj = applyVersion(applyProjectSettings(pbxproj), version)
  if (nextPbxproj !== pbxproj) {
    writeFileSync(pbxprojPath, nextPbxproj)
    changed.push('project.pbxproj')
  }
  return { skipped: false, changed }
}

/**
 * The version pair for this checkout: package.json's semver, and the commit
 * count on the current branch as a monotonic build number. `undefined` halves
 * are left untouched by applyVersion.
 */
export function resolveVersion(rootDir) {
  let marketingVersion
  try {
    marketingVersion = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf8')).version
  } catch {
    marketingVersion = undefined
  }
  let buildNumber
  try {
    buildNumber = execFileSync('git', ['rev-list', '--count', 'HEAD'], { cwd: rootDir, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim()
    if (!/^\d+$/.test(buildNumber)) buildNumber = undefined
  } catch {
    buildNumber = undefined
  }
  return { marketingVersion, buildNumber }
}

function main() {
  const rootDir = process.env.CAPACITOR_ROOT_DIR || resolve(__dirname, '..')
  const iosDir = resolve(rootDir, 'ios')
  const version = resolveVersion(rootDir)
  const result = configureIosProject(iosDir, { version })
  if (result.skipped) {
    console.log(`[configure-ios] no ios/ project at ${iosDir} — nothing to do (run \`npx cap add ios --packagemanager SPM\` first)`)
    return
  }
  const stamp = version.buildNumber ? `${version.marketingVersion} (${version.buildNumber})` : `${version.marketingVersion} (build number unchanged: git unavailable)`
  console.log(
    result.changed.length
      ? `[configure-ios] applied App Store config, version ${stamp}: ${result.changed.join(', ')}`
      : `[configure-ios] App Store config already applied, version ${stamp}`,
  )
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main()
